name: personal_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  universal_html: ^2.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resume.pdf
    - assets/image/
    - assets/logo/




